version: "3.1"
services:
  app:
    build: .
    restart: always
    container_name: mongorest-demo
    ports:
      - 8080:8080 # Replace the port of your application here if used
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always